# Generated by Django 5.0.6 on 2025-04-01 20:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        ("petitions", "0002_alter_petition_options_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetitionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introductory text for the petition page."
                    ),
                ),
                (
                    "petition",
                    models.ForeignKey(
                        help_text="Select the petition this page represents.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="petitions.petition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Petition Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
