# Generated by Django 5.0.6 on 2025-04-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_petitionpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Strona Główna"},
        ),
        migrations.AlterModelOptions(
            name="petitionpage",
            options={
                "verbose_name": "Strona Petycji",
                "verbose_name_plural": "Strony Petycji",
            },
        ),
    ]
