# Generated by Django 5.0.6 on 2025-03-29 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.PositiveIntegerField(help_text='Target number of signatures', validators=[django.core.validators.MinValueValidator(1)])),
                ('signature_count', models.PositiveIntegerField(default=0, help_text='Current number of signatures')),
                ('email_subject', models.CharField(help_text='Subject line for confirmation emails', max_length=255)),
                ('email_content', models.TextField(help_text='Content of the email sent after signing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetitionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Phone number with country code', max_length=20)),
                ('email_consent', models.BooleanField(default=False, help_text='Consent to receive emails')),
                ('phone_consent', models.BooleanField(default=False, help_text='Consent to receive phone calls or SMS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='petitions.petition')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('petition', 'email')},
            },
        ),
    ]
