# Generated by Django 5.0.6 on 2025-04-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petition",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Petition",
                "verbose_name_plural": "Petitions",
            },
        ),
        migrations.AlterModelOptions(
            name="petitionsignature",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Petition Signature",
                "verbose_name_plural": "Petition Signatures",
            },
        ),
    ]
