# Generated by Django 5.0.6 on 2025-04-01 20:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0002_alter_petition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="email_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Content of the email sent after signing"
            ),
        ),
    ]
